version: "3.9"

services:
  frontend:
    image: ${IMAGE_FRONT}
    restart: always
    ports:
      - "80:3000"
    volumes:
      - .:/usr/src/app

  postgres:
    image: "postgres:16.2"
    container_name: "whell_db"
    restart: always
    environment:
      POSTGRES_DB: "whell_db"
      POSTGRES_USER: ${DB_LOGIN}
      POSTGRES_PASSWORD: ${DB_PASS}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - db-data:/var/lib/postgresql/data

  spin-whell:
    image: ${IMAGE}
    restart: always
    environment:
      DB_LOGIN: ${DB_LOGIN}
      DB_PASS: ${DB_PASS}
      SPRING_PROFILES_ACTIVE: prod

volumes:
  db-data:
